__author__ = 'Ahmet Erkan ÇELİK'

from datetime import datetime
import math

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

startTime = datetime.now()
result = 0

pentagonal_numbers = []


def is_triangle_number(number):
    nn1 = number * 2  # n(n+1) elde etmek için
    n = int(math.sqrt(nn1))
    if nn1 == n * (n+1):
        return True
    else:
        return False


def is_pentagonal_number(number):
    n3n1 = number * 2  # n(3n−1) = 3n^2 - n  elde etmek için
    # 3n^2 - n - x = 0
    delta = 1 + (12 * n3n1)
    n = (1 + math.sqrt(delta)) / 6
    if n == int(n):
        return True
    else:
        return False


def is_hexagonal_number(number):
    #2n^2 -n - number = 0
    delta = 1 + 8 * number
    n = (1 + math.sqrt(delta)) / 4

    if n == int(n):
        return True
    else:
        return False

def generate_hexagonal_number(n):
    return n * (2 * n - 1)


n = 286
hn = generate_hexagonal_number(n)
while not is_triangle_number(hn) or not is_pentagonal_number(hn):
    n += 1
    hn = generate_hexagonal_number(n)

result = hn
print("Result is: %s" % (result))
print(datetime.now() - startTime)
exit()

