__author__ = 'Ahmet Erkan ÇELİK'

from datetime import datetime
import math

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

startTime = datetime.now()
result = 0

pentagonal_numbers = []


def generate_pentagonal_numbers():
    i = 1
    while True:
        yield (i * (3 * i - 1)) / 2
        i += 1


print("Result is: %s" % (result))
print(datetime.now() - startTime)
exit()

